### ISSUE TITLE
doesn't work in Safari

### ISSUE THREAD

**Issue by bobuk** [hackerkid/peerdium#1]
[Error] TypeError: Error creating RTCPeerConnection
	initializeRTCPeerConnection (webtorrent.min.js:1:218558)
	(anonymous function)
	r (webtorrent.min.js:1:218558)
	_createPeer (webtorrent.min.js:1:65705)
	n (webtorrent.min.js:1:64989)
	_generateOffers (webtorrent.min.js:1:65396)
	announce (webtorrent.min.js:1:59900)
	(anonymous function) (webtorrent.min.js:1:59655)
	p (webtorrent.min.js:1:88734)
	p
	s (webtorrent.min.js:1:87439)
	emit (webtorrent.min.js:1:90880)
	_onOpen (webtorrent.min.js:1:235231)
	onopen (webtorrent.min.js:1:232821)

**Comment by hackerkid** [comment]
Thanks for reporting. I am not sure it's an issue with iOS + safari. More likely to be a network issue. Maybe the ports are blocked by the ISP.
