### ISSUE TITLE
Consider storing encryption key in URL hash so it is not sent to the server

### ISSUE THREAD

**Issue by phiresky** [hackerkid/peerdium#3]
Currently the encryption key is stored in the path part of the URL, which is sent to the server and thus shows up in server logs etc. If you store it in the hash part of the url hash (`https://peerdium.com/magnethash#encryptionkey`) it will never be sent to the server.

Since decryption happens client-side anyways, this would make that more clear (and maybe even have positive legal implications). Or just put both the magnet hash and the encryption key in the url hash, that would work too.

`mega.co.nz` also does this. See also [encrypted-gist](https://github.com/phiresky/encrypted-gist) for an example.

**Comment by hackerkid** [comment]
@phiresky This is a great idea. I have time to do this after a few days. But if anyone is looking for an issue to work feel free to start working on this :)
