### ISSUE TITLE
Release unminified JS

### ISSUE THREAD

**Issue by makew0rld** [hackerkid/peerdium#4]
The JS in this project appears to be minified, all on one line, and obfuscated. This is a cool project, and providing the original js files would be more in the spirit of open-source and help others add to it or build upon it.

**Comment by hackerkid** [comment]
@makeworld-the-better-one The JS file which I wrote is https://github.com/hackerkid/peerdium/blob/master/static/js/editor.js. Its not minified. Rest all JS files are third-party dependencies and the source can be found in their own repos :)
