### ISSUE TITLE
What servers are used?

### ISSUE THREAD

**Issue by makew0rld** [hackerkid/peerdium#5]
I'm looking into the application, and I see it uses lots of tracker servers in the magnet URI, and that it also makes a request to https://young-sea-71500.herokuapp.com/, which contains credentials to access a twilio server, and twilio is communication company? It also mentions ice servers, are you referring to ICE used for NAT traversal? There's also the `hooli` file, which according to the commit is also somehow used in a GET request, to fetch ice servers. I don't understand how it all fits together. If you are using WebTorrent, shouldn't it Just Work serverlessly, because of WebRTC? I understand there might have been problems before, but it should be ok now, I thought. You might need to update the `webtorrent.min.js` file though

Also what is hooli?

**Comment by makeworld-the-better-one** [comment]
Also what is hooli?

**Comment by makeworld-the-better-one** [comment]
You might need to update the webtorrent file though

**Comment by makew0rld** [comment]
Ok a separate question, but why do you have downloaded JS files and also request online ones in `index.html`?

**Comment by makew0rld** [comment]
@hackerkid bump

**Comment by makew0rld** [comment]
@hackerkid Bump again! :full_moon:

**Comment by hackerkid** [comment]
@makeworld-the-better-one Sorry for replying late. I tried to reply to this or two times on mobile but was really hard to include the necessary links.

> I'm looking into the application, and I see it uses lots of tracker servers in the magnet URI, and that it also makes a request to https://young-sea-71500.herokuapp.com/, which contains credentials to access a twilio server, and twilio is communication company? It also mentions ice servers, are you referring to ICE used for NAT traversal?

Yeah. I use twilio turn/ice servers to make it work through NATS and firewalls. Peer discovery is really hard without using them in webtorrent/webrtc.

https://twitter.com/hackerkidx/status/996009992569274369
https://www.html5rocks.com/en/tutorials/webrtc/infrastructure/

> There's also the `hooli` file, which according to the commit is also somehow used in a GET request, to fetch ice servers.

All the files created are named as "hooli" for no particular reason :smile: 

> If you are using WebTorrent, shouldn't it Just Work serverlessly, because of WebRTC?

It should work in an ideal world. But in the world we live currently without services like Twilio for peer discovery :)

> Ok a separate question, but why do you have downloaded JS files and also request online ones in `index.html`?

Oops. No particular reason. I downloaded them for easier development in case of no internet. I think I later did a commit to use CDNs instead :)

**Comment by makew0rld** [comment]
@hackerkid thanks a lot! 

> no internet

This is my use case. There will also not be any NATing or firewalling, it will be in a mesh network. If I remove the code to access that server, and the hooli file, etc, can this still work? 

Also, the one question I still have my original comment is about tracker urls in the magnet URI. Are they really necessary? Again, in my no Internet environment, they won't be accessible. I'm hoping WebRTC can work without them through the DHT and stuff. 

This is all futile to some degree, as WebTorrent doesn't work with IPv6, which all mesh networks use. But I suppose I'm wondering about these things for when that support eventually does arrive.

**Comment by RangerMauve** [comment]
WebRTC won't work without the signaling servers. If you had known signaling servers in your no-internet setup, you might be able to get it to work.
